<div id="carousel-home" class="carrosselHome carousel slide">
			<!-- Indicators -->
			<ol class="carousel-indicators">
				<li data-target="#carousel-home" data-slide-to="0" class="active">
					<img src="{URL THUMB 1}">
				</li>
				<li data-target="#carousel-home" data-slide-to="1">
					<img src="{URL THUMB 2}">
				</li>
				<li data-target="#carousel-home" data-slide-to="2">
					<img src="{URL THUMB 3}">
				</li>
				<li data-target="#carousel-home" data-slide-to="3">
					<img src="{URL THUMB 4}">
				</li>
			</ol>
			<div class="carousel-inner">
				<div class="item active">
					<a href="#">
					<img src="{URL IMAGEM 1}" alt="..." class="carrosselImg">
					<div class="carousel-caption">
						<h3>{TITULO 1}</h3>
						<p>{DESCRICAO 1}</p>
					</div>
					</a>
				</div>
				<div class="item">
					<a href="#">
					<img src="{URL IMAGEM 2}" alt="..." class="carrosselImg">
					<div class="carousel-caption">
						<h3>{TITULO 2}</h3>
						<p>{DESCRICAO 2}</p>
					</div>
					</a>
				</div>
				<div class="item">
					<a href="#">
					<img src="{URL IMAGEM 3}" alt="..." class="carrosselImg">
					<div class="carousel-caption">
						<h3>{TITULO 3}</h3>
						<p>{DESCRICAO 3}</p>
					</div>
					</a>
				</div>
				<div class="item">
					<a href="#">
					<img src="{URL IMAGEM 4}" alt="..." class="carrosselImg">
					<div class="carousel-caption">
						<h3>{TITULO 4}</h3>
						<p>{DESCRICAO 4}</p>
					</div>
					</a>
				</div>
			</div>
			<a class="left carousel-control" href="#carousel-home" data-slide="prev">
				<span class="icon-prev"></span>
			</a>
			<a class="right carousel-control" href="#carousel-home" data-slide="next">
				<span class="icon-next"></span>
			</a>
		</div>