			<div class="chamadaH1">
				<a href="#">
					<img src="http://carsale.uol.com.br/novosite/images/home/jacj3hatch_h2.jpg">
					<h3>Titulo chamda</h3>
					<h4>carro golf</h4>
				</a>
			</div>
			<div class="chamadaH2">
				<a href="#">
					<img src="http://carsale.uol.com.br/novosite/images/home/slsmercedes_h3.jpg">
					<h3>Vignale</h3>
					<h4>vignale</h4>
				</a>
			</div>
			<div class="chamadaH2">
				<a href="#">
					<img src="http://carsale.uol.com.br/novosite/images/home/vignale_h3.jpg">
					<h3>Vignale</h3>
					<h4>vignale</h4>
				</a>
			</div>

<!-- USE OS TAMANHOS PARA CHAMADAS DIFERENTES: 
		P = 
		M = 
		G = 
			<!--div class="chamadaH1">
				<a href="#">
					<img src="http://carsale.uol.com.br/novosite/images/home/jacj3hatch_h2.jpg">
					<h3>Titulo chamda</h3>
					<h4>carro golf</h4>
				</a>
			</div>
			<div class="chamadaH2">
				<a href="#">
					<img src="http://carsale.uol.com.br/novosite/images/home/slsmercedes_h3.jpg">
					<h3>Vignale</h3>
					<h4>vignale</h4>
				</a>
			</div>
			<div class="chamadaH2">
				<a href="#">
					<img src="http://carsale.uol.com.br/novosite/images/home/vignale_h3.jpg">
					<h3>Vignale</h3>
					<h4>vignale</h4>
				</a>
			</div-->